### ISSUE TITLE
Official doc link is outdated

### ISSUE THREAD

**Issue by XeniaGabriela** [IdentityPython/idpy-oidc#88] opened 2023-11-25 23:57 UTC
Dear Roland, 

[Official Documentation](https://idpyoidc.readthedocs.io/) results in a not found error:

![image](https://github.com/IdentityPython/idpy-oidc/assets/13744209/b08c0f09-46ad-42ba-afd0-00392aaeb020)

Kind regards,

Xenia

**Comment by c00kiemon5ter** [comment] 2023-11-26 08:34
duplicate of #84 

fixed by #85

**Closed as completed by c00kiemon5ter** 2023-11-26 08:34 UTC
